# Build a Google Play-ready signed Android App Bundle (AAB).

$ErrorActionPreference = "Stop"

$env:ANDROID_HOME = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { "$env:LOCALAPPDATA\Android\Sdk" }
$env:NDK_HOME = if ($env:NDK_HOME) { $env:NDK_HOME } else { "$env:ANDROID_HOME\ndk\26.1.10909125" }
$env:JAVA_HOME = if ($env:JAVA_HOME) { $env:JAVA_HOME } else { "C:\Program Files\Microsoft\jdk-17.0.19.10-hotspot" }

$ndkBin = Join-Path $env:NDK_HOME "toolchains\llvm\prebuilt\windows-x86_64\bin"
$env:PATH = "$ndkBin;$env:PATH"
$clang = Join-Path $ndkBin "aarch64-linux-android21-clang.cmd"
$clangxx = Join-Path $ndkBin "aarch64-linux-android21-clang++.cmd"
$llvmAr = Join-Path $ndkBin "llvm-ar.exe"
$llvmRanlib = Join-Path $ndkBin "llvm-ranlib.exe"

$env:CC_aarch64_linux_android = $clang
$env:CXX_aarch64_linux_android = $clangxx
$env:AR_aarch64_linux_android = $llvmAr
$env:RANLIB_aarch64_linux_android = $llvmRanlib
$env:CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = $clang
$env:CARGO_TARGET_AARCH64_LINUX_ANDROID_AR = $llvmAr

$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$androidDir = Join-Path $root "src-tauri\gen\android"
$keystore = Join-Path $androidDir "scrollhub-upload.jks"
$keystoreProps = Join-Path $androidDir "keystore.properties"
$credentialsFile = Join-Path $androidDir "UPLOAD_KEY_BACKUP.txt"
$keyAlias = "scrollhub-upload"
$storePass = "ScrollHub-Upload-2026!"

function Invoke-Checked([scriptblock]$Block, [string]$Label) {
    & $Block
    if ($LASTEXITCODE -ne 0) {
        throw "$Label failed with exit code $LASTEXITCODE"
    }
}

function Ensure-UploadKeystore {
    if ((Test-Path $keystore) -and (Test-Path $keystoreProps)) {
        Write-Host "Using existing Play upload keystore."
        return
    }

    Write-Host "Creating Play upload keystore (first-time setup)..."
    & "$env:JAVA_HOME\bin\keytool.exe" -genkeypair -v `
        -keystore $keystore `
        -storepass $storePass `
        -keypass $storePass `
        -alias $keyAlias `
        -keyalg RSA `
        -keysize 2048 `
        -validity 10000 `
        -dname "CN=ScrollHub, OU=Mobile, O=ScrollHub, L=Unknown, ST=Unknown, C=US"
    if ($LASTEXITCODE -ne 0) { throw "keytool failed" }

    @(
        "password=$storePass"
        "keyAlias=$keyAlias"
        "storeFile=scrollhub-upload.jks"
    ) | Set-Content -Path $keystoreProps -Encoding ASCII

    @(
        "ScrollHub Google Play upload key"
        "================================"
        ""
        "BACK UP THESE FILES. You need them for every Play Store update."
        ""
        "Keystore file: $keystore"
        "Key alias:     $keyAlias"
        "Password:      $storePass"
        ""
        "Also enroll in Play App Signing in Google Play Console so Google"
        "holds the app signing key and you only manage this upload key."
    ) | Set-Content -Path $credentialsFile -Encoding UTF8

    Write-Host ""
    Write-Host "IMPORTANT: Back up your upload keystore and password."
    Write-Host "Saved reference: $credentialsFile"
    Write-Host ""
}

Ensure-UploadKeystore

# Regenerate tauri.properties from tauri.conf.json version settings.
$tauriConf = Get-Content (Join-Path $root "src-tauri\tauri.conf.json") -Raw | ConvertFrom-Json
$versionName = $tauriConf.version
$versionCode = if ($tauriConf.bundle.android.versionCode) {
    [string]$tauriConf.bundle.android.versionCode
} else {
    $parts = $versionName.Split(".")
    while ($parts.Count -lt 3) { $parts += "0" }
    [string]([int]$parts[0] * 1000000 + [int]$parts[1] * 1000 + [int]$parts[2])
}
$propsPath = Join-Path $root "src-tauri\gen\android\app\tauri.properties"
@(
    "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY."
    "tauri.android.versionName=$versionName"
    "tauri.android.versionCode=$versionCode"
) | Set-Content -Path $propsPath -Encoding ASCII
Write-Host "Android version: $versionName ($versionCode)"

Write-Host "Syncing launcher icons..."
Invoke-Checked { powershell -ExecutionPolicy Bypass -File scripts/sync-android-icons.ps1 } "Icon sync"

Write-Host "Building frontend..."
Invoke-Checked { npm run build } "Frontend build"

Write-Host "Syncing web assets into Android assets..."
$assetDir = Join-Path $root "src-tauri\gen\android\app\src\main\assets"
if (Test-Path $assetDir) {
    Get-ChildItem $assetDir -Exclude "tauri.conf.json" | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
}
New-Item -ItemType Directory -Force -Path $assetDir | Out-Null
Copy-Item -Path (Join-Path $root "dist\*") -Destination $assetDir -Recurse -Force
Copy-Item (Join-Path $root "src-tauri\tauri.conf.json") (Join-Path $assetDir "tauri.conf.json") -Force

Write-Host "Building Rust library for aarch64..."
Push-Location src-tauri
Invoke-Checked { cargo clean -p scrollhub } "Cargo clean"
Invoke-Checked { cargo build --release --target aarch64-linux-android --lib --features "tauri/custom-protocol" } "Cargo Android build"
Pop-Location

$src = Join-Path $root "src-tauri\target\aarch64-linux-android\release\libscrollhub_lib.so"
if (-not (Test-Path $src)) {
    throw "Missing native library: $src"
}
$destDir = Join-Path $root "src-tauri\gen\android\app\src\main\jniLibs\arm64-v8a"
$dest = Join-Path $destDir "libscrollhub_lib.so"
New-Item -ItemType Directory -Force -Path $destDir | Out-Null
Copy-Item -Path $src -Destination $dest -Force
Write-Host "Copied native library into jniLibs"

Write-Host "Running Gradle (signed universal release AAB)..."
Push-Location src-tauri\gen\android
Invoke-Checked {
    .\gradlew.bat bundleUniversalRelease `
        -x rustBuildUniversalRelease `
        -x rustBuildArm64Release `
        -x rustBuildArmRelease `
        -x rustBuildX86Release `
        -x rustBuildX86_64Release
} "Gradle AAB build"
Pop-Location

$aabSrc = Join-Path $root "src-tauri\gen\android\app\build\outputs\bundle\universalRelease\app-universal-release.aab"
if (-not (Test-Path $aabSrc)) {
    throw "AAB output not found: $aabSrc"
}

$outDir = Join-Path $root "release-assets"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$aabOut = Join-Path $outDir "ScrollHub-v$versionName-google-play.aab"
Copy-Item $aabSrc $aabOut -Force

Write-Host ""
Write-Host "Google Play AAB ready: $aabOut"
Write-Host ""
Write-Host "Upload in Play Console:"
Write-Host "  Production > Create new release > Upload app bundle"
Write-Host "  Package: com.sojii.scrollhub | Version: $versionName ($versionCode)"
